## container build, no sudo
sudo: false

language: cpp 

compiler: 
    - gcc 
    - clang

os:
    - linux

cache:
  apt:
  ccache:
  directories:

env:
    global:
        - GCC_VERSION=5
        - CXXFLAGS=-std=c++11
        - CFLAGS=-std=c99

branches:
    only:
        - master

before_install:
    -   if [ ${CC} != "clang" ]; then
            export CC=/usr/bin/gcc-${GCC_VERSION} CXX=/usr/bin/g++-${GCC_VERSION};
            C=gcc;
        fi


addons:
 apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
# ensure these match GCC_VERSION
      - gcc-5
      - g++-5
      - binutils
      - gawk
      - build-essential
      - wget
      - libtool
      - flex


before_script:
    - echo $LANG
    - echo $LC_ALL
    - wget --no-check-certificate http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
    - mkdir $HOME/bison
    - tar -xf bison-3.0.4.tar.gz; cd bison-3.0.4; ./configure --prefix=$HOME/bison; make -j; cd..;
    - export PATH=$PWD/bison/bin:$PATH
    - bison --version
script:
    - ${CC} --version ; ${CXX} --version; 
    - env
    - make
    - cd test; ./test0.pl; cd ..
